"""add require_post_approval to Team

Revision ID: b65e05946a9e
Revises: 2e79fa356ea7
Create Date: 2026-08-31 11:30:28.455298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65e05946a9e'
down_revision: Union[str, None] = '2e79fa356ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('require_post_approval', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'require_post_approval')
    # ### end Alembic commands ###
